apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-ingestion-pipeline.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "data-ingestion-pipeline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
    {{- include "data-ingestion-pipeline.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-ingestion-pipeline.fullname" . }}-web
  labels:
    app.kubernetes.io/component: web
    {{- include "data-ingestion-pipeline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: web
    {{- include "data-ingestion-pipeline.selectorLabels" . | nindent 4 }}
